const brandColors = {
  'brand-1': '#33415C',
  'brand-2': '#5C677D',
  'brand-3': '#7D8597',
  'brand-4': '#979DAC',
  'brand-5': '#238FFB',
  'brand-6': '#0466C8',
  'brand-7': '#0353A4',
  'brand-8': '#023E7D',
  'brand-9': '#002855',
  'brand-10': '#001845',
  'brand-11': '#001233',
  'brand-alt-1': '#33415C',
  'brand-alt-2': '#5C677D',
  'brand-alt-3': '#7D8597',
  'brand-alt-4': '#979DAC',
  'brand-contrast': '#EEE',
  'accent-1': '#06D6A0',
  'accent-2': '#FFD166',
  'accent-3': '#EF476F',
  'accent-4': '#118AB2',
};

const genericColors = {
  aqua: '#7fdbff',
  blue: '#0074d9',
  lime: '#01ff70',
  navy: '#001f3f',
  teal: '#39cccc',
  olive: '#3d9970',
  green: '#2ecc40',
  red: '#ff4136',
  maroon: '#85144b',
  orange: '#ff851b',
  purple: '#b10dc9',
  yellow: '#ffdc00',
  fuchsia: '#f012be',
  gray: '#aaaaaa',
  white: '#ffffff',
  black: '#111111',
  silver: '#dddddd',
};

const shades = {
  'shade-1': '#F8F9FA',
  'shade-2': '#E9ECEF',
  'shade-3': '#DEE2E6',
  'shade-4': '#CED4DA',
  'shade-5': '#ADB5BD',
  'shade-6': '#6C757D',
  'shade-7': '#495057',
  'shade-8': '#343A40',
  'shade-9': '#212529',
};

const colors = {
  ...brandColors,
  ...genericColors,
  ...shades,
  brand: 'brand-5',
  background: {
    dark: '#111111',
    light: '#FFFFFF',
  },
  'background-back': {
    dark: '#111111',
    light: '#EEEEEE',
  },
  'background-front': {
    dark: '#222222',
    light: '#FFFFFF',
  },
  'background-contrast': {
    dark: '#FFFFFF11',
    light: '#11111111',
  },
  text: { light: 'brand-3' },
  'text-strong': { light: 'brand-2' },
  'text-weak': { light: 'brand-4' },
  'text-xweak': { light: 'brand-4' },
  border: { light: 'shade-2' },
  control: 'brand-5',
  'active-background': 'background-contrast',
  'active-text': 'brand-1',
  'selected-background': 'brand',
  'selected-text': 'white',
  'status-critical': '#FF4040',
  'status-warning': '#FFAA15',
  'status-ok': '#00C781',
  'status-unknown': '#CCCCCC',
  'status-disabled': '#CCCCCC',
  'graph-0': 'brand',
  'graph-1': 'status-warning',
  focus: 'brand-5',
  icon: {
    dark: 'currentColor',
    light: 'currentColor',
  },

  heading1: brandColors['brand-1'],
  heading2: brandColors['brand-2'],
  heading3: brandColors['brand-2'],
  heading4: brandColors['brand-2'],
  heading5: brandColors['brand-2'],
  heading6: brandColors['brand-2'],

  link: brandColors['brand-5'],
  'hovered-link': brandColors['brand-6'],
  'active-link': brandColors['brand-7'],

  'primary-button-color': brandColors['brand-2'],
  'primary-button-border-color': brandColors['brand-2'],
  'primary-button-text-color': '#fff',
  'secondary-button-color': brandColors['brand-3'],
  'secondary-button-border-color': brandColors['brand-3'],
  'secondary-button-text-color': '#fff',
  'default-button-color': 'transparent',
  'default-button-border-color': brandColors['brand-4'],
  'default-button-text-color': brandColors['brand-3'],
};

export default colors;
