export * from './layout';
export const boxProps = [
  {
    name: 'align',
    allowedValues: ['start', 'center', 'end', 'baseline', 'stretch'],
  },
  {
    name: 'alignContent',
    allowedValues: ['start', 'center', 'end', 'between', 'around', 'stretch'],
    defaultValue: 'stretch',
  },
  {
    name: 'alignSelf',
    allowedValues: ['start', 'center', 'end', 'stretch'],
  },
  {
    name: 'basis',
    allowedValues: [
      'xxsmall',
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      'full',
      '1/2',
      '1/3',
      '2/3',
      '1/4',
      '2/4',
      '3/4',
      'auto',
    ],
  },
  {
    name: 'direction',
    allowedValues: [
      'row',
      'column',
      'row-responsive',
      'row-reverse',
      'column-reverse',
    ],
    defaultValue: 'column',
  },
  {
    name: 'fill',
    allowedValues: ['horizontal', 'vertical', true, false],
  },
  {
    name: 'flex',
    allowedValues: [
      'grow',
      'shrink',
      true,
      false,
      { grow: 'number', shrink: 'number' },
    ],
  },
  {
    name: 'gap',
    allowedValues: [
      'none',
      'xxsmall',
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      'any CSS size',
    ],
  },
  { name: 'gridArea', allowedValues: ['string'], defaultValue: '' },
  {
    name: 'height',
    allowedValues: [
      'xxsmall',
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      'xxlarge',
      { min: '...', max: '...' },
      'any CSS size',
    ],
  },
  {
    name: 'justify',
    allowedValues: [
      'around',
      'between',
      'center',
      'end',
      'evenly',
      'start',
      'stretch',
    ],
    defaultValue: 'stretch',
  },
  {
    name: 'margin',
    allowedValues: [
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      {
        vertical: '...',
        horizontal: '...',
        top: '...',
        bottom: '...',
        left: '...',
        right: '...',
      },
    ],
  },
  {
    name: 'overflow',
    allowedValues: [
      'auto',
      'hidden',
      'scroll',
      'visible',
      'any CSS overflow',
      { vertical: '...', horizontal: '...' },
    ],
  },
  {
    name: 'pad',
    allowedValues: [
      'none',
      'xxsmall',
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      'any CSS size',
      {
        vertical: '...',
        horizontal: '...',
        top: '...',
        bottom: '...',
        left: '...',
        right: '...',
      },
    ],
    defaultValue: 'none',
  },
  { name: 'responsive', allowedValues: [true, false], defaultValue: true },
  {
    name: 'width',
    allowedValues: [
      'xxsmall',
      'xsmall',
      'small',
      'medium',
      'large',
      'xlarge',
      'xxlarge',
      { min: '...', max: '...' },
      'any CSS size',
    ],
  },
  {
    name: 'wrap',
    allowedValues: [true, false, 'reverse'],
    defaultValue: false,
  },
];
